[theme]
backgroundColor = "white" # ==> PROBLEME DE COULEUR DANS LES COMBOBOX
secondaryBackgroundColor = "white" # ==> IMPOSSIBLE A MODIFI

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[ui]
hideTopBar = true